language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

before_install:
  - pip install pip -U
  - pip install poetry

install:
  - poetry install -v

script: pytest -x tests
